Add test case for getActiveParticipationInvitation with multiple part…
cph-cachet/carp.core-kotlin pull request #483
Opened 2024-09-24 14:05 UTC by yuanchen233

…icipation

2024-09-25 18:30 UTC, Whathecode requested changes

2024-09-25 18:30 UTC, Whathecode commented on carp.deployments.core/src/commonTest/kotlin/dk/cachet/carp/deployments/application/ParticipationServiceTest.kt
> +        val protocol = createSinglePrimaryDeviceProtocol()
It's best for integration tests to try to reflect real-world scenarios. Especially, given that these tests are also used to output _example JSON requests_ which are included in releases (generated through `OutputParticipationServiceTestRequests`, but added manually), and these output JSON requests in turn are used for regression testing when API versions are bumped to test API migrations (`BackwardsCompatibilityTest`).

It's not very common/expected (though possible) to have a study protocol with a single device, which is assigned to both a "father" and "mother". Instead, we could make this test more representative of a multi-device scenario, which in addition also increases code coverage on top of what is already tested in the test above.

2024-09-25 18:33 UTC, Whathecode commented on carp.deployments.core/src/commonTest/kotlin/dk/cachet/carp/deployments/application/ParticipationServiceTest.kt
> +                AssignedTo.All,
This means that both accounts will be assigned to _all_ roles (both "father" and "mother"), which while possible, is misleading and makes this example less sensical.

2024-09-26 18:22 UTC, Whathecode submitted a review, later dismissed
To keep the test focused, I added a `createTwoDevicesAndRolesProtocol()` test helper, which is likely to also be useful in future test cases.

I added additional assertions to verify _both_ accounts, as well as the devices they were assigned.

Lastly, I fixed to code styles to follow the non-idiomatic style of this project. ;) I think the static checker only checks for it in main sources, or it failed here. Either way: I'll gladly polish minor stuff like that in any PR you send along. :)

2024-09-26 18:27 UTC, Whathecode approved these changes
I added an exception for test sources for detekt flagging destructuring operations > 3 fields.

2024-09-26 18:35 UTC, merged

2024-09-26 20:04 UTC, yuanchen233 commented
Thank you for the explanation and commentnt.

> To keep the test focused, I added a `createTwoDevicesAndRolesProtocol()` test helper, which is likely to also be useful in future test cases.
> 
I thought about re-using `createComplexProtocol` and expose Roles, but this information is not used by other test cases. This multi role protocol should also be relevant when adding more `InputDataType`.

I'll be adopting to the decision making logic (and maybe code style here)