Add additionalSpecifications field to DeviceRegistration
cph-cachet/carp.core-kotlin pull request #484
Opened 2024-09-25 10:13 UTC by yuanchen233

As discussed in #431, adding a `additionalSpecifications` field to `DeviceRegistration`. This allows to keep additional specification data when register device and access them later on in `StudyDeploymentStatus.deviceStatusList`

2024-09-27 16:18 UTC, yuanchen233 commented
For `DeviceRegistrationTest`, original test cases were kept to cover situations when `additionalSpecifications` is null; same for `GenerateExampleRequests` for rpc, additionalSpecifications is only added to one of the deviceRegistration.

2024-09-30 19:38 UTC, Whathecode requested changes
See comments; I already fixed those (you can resolve them after reading them).

In addition, I squashed three of the commits into one. Each commit ideally should pass all tests/be a cohesive whole. The last commit was a correct separate commit. 👍 I hope/presume you didn't have other changes on this branch, so I force pushed. Apologies if you did (as that can cause conflicts). Make sure to use `git pull --rebase`.

But, I see two other concerns before this can be merged:
- I don't recall 100% whether or not we need `@Required` on the field. I vaguely remember it may be needed for some scenario, maybe "unknown polymorphic serialization". I need to dig up some old issues/documentation.
- You didn't test whether `additionalSpecification` actually gets serialized as a JSON object (instead as a string with escaped `\"` chars, etc.). I put a breakpoint and apparently it doesn't. I suspect that is because the serializer used for that field is not "inherited" as you would expect it. I need to dig in to kotlinx serialization documentation to refresh my memory.

2024-09-30 19:38 UTC, Whathecode commented on carp.common/src/commonTest/kotlin/dk/cachet/carp/common/infrastructure/serialization/DeviceRegistrationTest.kt
> +        return DefaultDeviceRegistration( deviceDisplayName, additionalSpecifications )
There's a bug here. Or, at least, this doesn't do what the code implies. The second parameter is not `additionalSpecifications`, but `deviceId`.

And, `deviceId` was purposefully added as the last parameter, as in the vast majority of cases you want to not specify that yourself. Maintaining it last would have made this less likely to happen. :)

Furthermore, this method is not really common to both places where it is used. The context is different, and in this case, inlining it and making it more specific to the exact thing being tested makes more sense.

2024-09-30 19:38 UTC, Whathecode commented on carp.common/src/commonTest/kotlin/dk/cachet/carp/common/infrastructure/serialization/DeviceRegistrationTest.kt
> +    fun can_serialize_and_deserialize_not_null_additional_information()
Unfortunately we don't have support for parameterized tests. At least, back when I set up this project, there was no multiplatform test framework which provided that.

But, this would be more appropriate here. Check out how I reworked this to a poor man's version of the same. :) The downside is it doesn't report individual test results, but I think that is a small price to pay for maintainability/removing code duplication.

Consider it a potentially useful investigation to look at the current status of parameterized tests in kotlin multiplatform.

2024-09-30 19:38 UTC, Whathecode commented on carp.common/src/commonTest/kotlin/dk/cachet/carp/common/infrastructure/serialization/DeviceRegistrationTest.kt
> +        serialized = serialized.replace( "dk.cachet.carp.common.application.devices.DefaultDeviceRegistration", "com.unknown.CustomRegistration" )
Not that you could have known, but I've created `makeUnknown` test helpers before to help setting this  up as it become a recurring thing.

2024-09-30 19:38 UTC, Whathecode commented on rpc/schemas/common/devices/DeviceRegistration.json
> +        "additionalSpecifications": { "type": [ "object", "string", "null" ] }
This can reference `ApplicationData.json` for consistency with other places where this is used.

2024-09-30 19:38 UTC, Whathecode commented on rpc/src/main/kotlin/dk/cachet/carp/rpc/GenerateExampleRequests.kt
> +    additionalSpecifications = "model: 1234"
Similar to `applicationData = "{\"uiTheme\": \"black\"}"` and other "application data" fields for which examples are created here, let's make this a representative JSON string.

2024-09-30 19:44 UTC, Whathecode commented
Regarding `@Required`, I [found something relevant here](https://github.com/cph-cachet/carp.core-kotlin/issues/169#issuecomment-915341765).

> Missing `@Required` attributes on fields which should always be serialized but had values assigned by initializers. These fields are needed since the backend does not necessarily have the concrete types available, and these fields are hence not optional. Applying `@Required` solves that.

2024-10-01 19:43 UTC, yuanchen233 commented on carp.common/src/commonTest/kotlin/dk/cachet/carp/common/infrastructure/serialization/DeviceRegistrationTest.kt
> +        serialized = serialized.replace( "dk.cachet.carp.common.application.devices.DefaultDeviceRegistration", "com.unknown.CustomRegistration" )
Now I know the hidden treasure, each time I visit `CreateTestObjects.kt`  I learn something new, as I totally lost track which subsystem I find them.

2024-10-01 21:29 UTC, yuanchen233 commented
> In addition, I squashed three of the commits into one. Each commit ideally should pass all tests/be a cohesive whole. The last commit was a correct separate commit. 
>
Got it, I was expecting a 'squash and merge' when this branch is done, but saw a TODO warning when pushing. I didn't give much thought if those changes should be applied here after having fun reading that serialization issue


> 
> Now I'm actually wondering whether `DeviceRegistration.deviceDisplayName` even ever needed `@Required`. It didn't seem like I considered/questioned that [in the related PR](https://github.com/cph-cachet/carp.core-kotlin/pull/350). I'm thinking _not_ applying `@Required` (as you did here) is correct, and adding it for `deviceDisplayName` may have been erroneous due to a naive mimicking of surrounding code.
> 
You mentioned in this PR `deviceDisplayName` was initially _not optional_, then the `@Required` annotation makes sense there, initially at least. I tested with and with out the annotation, both passes all the tests we currently have. 

Regarding removing `@Required` from `.deviceDisplayName`, My concern is backward compatibility, especially JS target. As [Defaults are not encoded](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded), default null value will become undefined.

> And, regarding the `ApplicationDataSerializer` not kicking in, my intuition seems right:
> I suspect that is because the serializer used for that field is not "inherited" as you would expect it.
> 
> For this to work as expected, you would have to apply `@Serializable( ApplicationDataSerializer::class )` to all extending classes of `DeviceRegistration`. 
...
> That would be a bit unfortunate if there is no way around this. It would be worthwhile checking the kotlinx serialization documentation to see whether they have any (new) features which can avoid the need for doing this.

This actually makes sense, as how kotlinx.serialization works with generic type parameters/abstract class, a serializer is required for each type/subclass. Note we also have `@Serializale` annotation for each subclass of `DeviceRegistration`. If `@Serializable(with=..)` for a field can be inherited, I would expect subclass also inherite `@Serializable` form superclass (which is not the case).

One work around I can think of is creating a new datatype/class to handle `ApplicationData` instead of using `String`, then we can set and enforce serializer for that class. The annotation will then only needed once when we declare the class, and `ApplicationDataSerializer` will be used as the default serializer, instead of `String.serializer()`.

2024-10-02 08:09 UTC, Whathecode commented on carp.common/src/commonTest/kotlin/dk/cachet/carp/common/infrastructure/serialization/DeviceRegistrationTest.kt
> +        serialized = serialized.replace( "dk.cachet.carp.common.application.devices.DefaultDeviceRegistration", "com.unknown.CustomRegistration" )
Yeah, there is some redundancy here. For more information, check this issue: https://github.com/cph-cachet/carp.core-kotlin/issues/23 Specifically: https://github.com/cph-cachet/carp.core-kotlin/issues/23#issuecomment-556017519

2024-10-02 08:24 UTC, Whathecode commented
> One work around I can think of is creating a new datatype/class to handle ApplicationData instead of using String, then we can set and enforce serializer for that class. The annotation will then only needed once when we declare the class, and ApplicationDataSerializer will be used as the default serializer, instead of String.serializer().

Good idea!

I think I considered it in the past. Maybe I didn't pursue it since without inheritance there was no clear benefit. I shortly looked for past considerations, but couldn't find any, [only the PR where it was introduced](https://github.com/cph-cachet/carp.core-kotlin/pull/263).

So, definitely worthwhile giving this a go! You may want to do that as a separate PR preceding this one. But, also fine as separate commit within this one. Whichever you prefer. :) I won't force push anymore without checking in with you; the branch is yours.

2024-10-04 13:43 UTC, yuanchen233 commented
> Regarding removing `@Required` from `.deviceDisplayName`, My concern is backward compatibility, especially JS target. As [Defaults are not encoded](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded), default null value will become undefined.

I ran some tests and it is the case:

```
carp.deployments.core/src/commonTest/resources/test-requests/DeploymentService/1.0/DeploymentServiceTest/
createStudyDeployment_registers_preregistered_devices.json
Request #3 returned the wrong response. ==> expected: 

<{"deviceConfiguration":{...},"registration":{"__type":"dk.cachet.carp.common.application.devices.DefaultDeviceRegistration","registrationCreatedOn":"2022-04-04T15:03:22.341209Z","deviceDisplayName":null,"deviceId":"17124c6e-c8e0-457e-9b6b-f66860c4b666"},"connectedDevices":[{"__type":"dk.cachet.carp.common.infrastructure.test.StubDeviceConfiguration","roleName":"Connected"}],"connectedDeviceRegistrations":{"Connected":{"__type":"dk.cachet.carp.common.application.devices.DefaultDeviceRegistration","registrationCreatedOn":"2022-04-04T15:03:22.340210600Z","deviceDisplayName":null,"deviceId":"26d56d0e-2d78-4c5a-a428-bfd85d05da77"}}}> 
but was: 
<{"deviceConfiguration":{...},"registration":{"__type":"dk.cachet.carp.common.application.devices.DefaultDeviceRegistration","registrationCreatedOn":"2022-04-04T15:03:22.341209Z","deviceId":"17124c6e-c8e0-457e-9b6b-f66860c4b666"},"connectedDevices":[{"__type":"dk.cachet.carp.common.infrastructure.test.StubDeviceConfiguration","roleName":"Connected"}],"connectedDeviceRegistrations":{"Connected":{"__type":"dk.cachet.carp.common.application.devices.DefaultDeviceRegistration","registrationCreatedOn":"2022-04-04T15:03:22.340210600Z","deviceId":"26d56d0e-2d78-4c5a-a428-bfd85d05da77"}}}>
```

`"deviceDisplayName":null` is missing due to kotlinx serializer not generating default values. If we want to change this, I think it's best to create another issue and plan to fix it for the next major release version? As far as I remember we don't support backward compatibility cross major versions.

2024-10-05 09:40 UTC, Whathecode commented
That can easily resolved with a version migration, so only a minor version bump is needed. 

But, definitely out of scope here. 👍

2024-10-06 16:48 UTC, merged